### ISSUE TITLE
the 4.0 version is a downgrade 

### ISSUE THREAD

**Issue by Epizefiri** [stepanenko3/nova-json#16] opened 2023-09-25 09:36 UTC
Hello there,
I was using the 3.x version of nova-json and this new version is an absolute downgrade.
the 4.0 Is not backward compatible with the 3.0 and there isn't a way ( or there isn't documentation ) to have no repeatable fields.

What's the reason of such a downgrade?

**Comment by stepanenko3** [comment] 2023-09-25 17:36
@Epizefiri at the moment the package has been completely redesigned, version 3.0 was a duplicate of another package, and version 4.0 is a completely redesigned version that extends the work with JSON fields. The previous version had many bugs that lasted from the 3rd version of Nova, in this version they are fixed. Also, the new version gives more opportunities to work with fields than the previous one.

**Comment by Epizefiri** [comment] 2023-09-25 18:17
What about not repeatable fields?


Il giorno lun 25 set 2023 alle ore 19:37 Artem Stepanenko <
***@***.***> ha scritto:

**Comment by stepanenko3** [comment] 2023-09-25 19:06
@Epizefiri,
Please, see the [big example](https://github.com/stepanenko3/nova-json#the-big-example)

**Closed** 2023-12-13 08:53 UTC
