### ISSUE TITLE
Version 3.1 is Gone

### ISSUE THREAD

**Issue by simone-bianco** [stepanenko3/nova-json#15] opened 2023-07-18 14:21 UTC
Hello, is version 3.1 gone? My project still uses that version

**Comment by stepanenko3** [comment] 2023-07-18 18:19
Hi, @simone-bianco

This package has been completely redesigned from 0

The version you're talking about was a duplicate of another package, updated to Nova 4

**Closed by stepanenko3** 2023-07-18 18:19 UTC

**Comment by Epizefiri** [comment] 2023-11-15 14:35
what's the name of the package?
